version: "3.4"

services:
  database:
    container_name: project110_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project110_net
    volumes:
      - project110_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project110
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: project110_backend
    image: jeanbarcellos/desafio-project110:latest
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - project110_net
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=project110
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - APP_URL=http://localhost:8080
      - APP_KEY='ZGVtby1zZWNyZXQtZGV2LTEyMzQ1Ng=='
      - APP_JWT_EXPIRATION=1440
    volumes:
      - project110_backend_data:/logs

networks:
  project110_net:
    name: project110_net
    driver: bridge

volumes:
  project110_database_data:
    name: project110_database_data
    driver: local

  project110_backend_data:
    name: project110_backend_data
    driver: local