server:
  port: ${PORT:8080}

spring:
  application:
    name: project110-service-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5532}/${DB_NAME:project110}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

  jpa:
    hibernate:
      ddl-auto: none # update, create-drop, none
    show-sql: false
    properties:
      hibernate:
        format-sql: false
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none # create
              create-target: create-schema.sql
              create-source: metadata

  flyway:
    enabled: true
    default-schema: project110

  jackson:
    default-property-inclusion: non-null

  mvc:
    log-resolved-exception: false

  main:
    banner-mode: off

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # devtools:
  #   restart:
  #     exclude: redis

springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: alpha
    tagsSorter: alpha


app-config:
  name: @project.name@
  description: @project.description@
  version: @project.version@

  cache:
    default:
      ttl: 1 # horas
    categories:
      name: "categories"
      ttl: 24 # horas
    products:
      name: "products"
      ttl: 16 # horas
    persons:
      name: "persons"
      ttl: 8 # horas